<?php

namespace Database\Seeders;

use App\Models\Currencs;
use Illuminate\Database\Seeder;

class CurrencsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currency = [
            [ "code" => "USD", "name" => "United States dollar", "symbol" => "$" ],
            [ "code" => "AFN", "name" => "Afghan afghani", "symbol" => "؋" ],
            [ "code" => "EUR", "name" => "Euro", "symbol" => "€" ],
            [ "code" => "ALL", "name" => "Albanian lek", "symbol" => "L" ],
            [ "code" => "DZD", "name" => "Algerian dinar", "symbol" => "د.ج" ],
            [ "code" => "AOA", "name" => "Angolan kwanza", "symbol" => "Kz" ],
            [ "code" => "AWG", "name" => "Aruban florin", "symbol" => "ƒ" ],
            [ "code" => "BHD", "name" => "Bahraini dinar", "symbol" => ".د.ب" ],
            [ "code" => "BDT", "name" => "Bangladeshi taka", "symbol" => "৳" ],
            [ "code" => "BYN", "name" => "New Belarusian ruble", "symbol" => "Br" ],
            [ "code" => "BTN", "name" => "Bhutanese ngultrum", "symbol" => "Nu." ],
            [ "code" => "BOB", "name" => "Bolivian boliviano", "symbol" => "Bs." ],
            [ "code" => "BWP", "name" => "Botswana pula", "symbol" => "P" ],
            [ "code" => "BRL", "name" => "Brazilian real", "symbol" => "R$" ],
            [ "code" => "BGN", "name" => "Bulgarian lev", "symbol" => "лв" ],
            [ "code" => "BIF", "name" => "Burundian franc", "symbol" => "Fr" ],
            [ "code" => "KHR", "name" => "Cambodian riel", "symbol" => "៛" ],
            [ "code" => "CVE", "name" => "Cape Verdean escudo", "symbol" => "Esc" ],
            [ "code" => "CNY", "name" => "Chinese yuan", "symbol" => "¥" ],
            [ "code" => "KMF", "name" => "Comorian franc", "symbol" => "Fr" ],
            [ "code" => "CDF", "name" => "Congolese franc", "symbol" => "Fr" ],
            [ "code" => "CRC", "name" => "Costa Rican colón", "symbol" => "₡" ],
            [ "code" => "HRK", "name" => "Croatian kuna", "symbol" => "kn" ],
            [ "code" => "CZK", "name" => "Czech koruna", "symbol" => "Kč" ],
            [ "code" => "DKK", "name" => "Danish krone", "symbol" => "kr" ],
            [ "code" => "DJF", "name" => "Djiboutian franc", "symbol" => "Fr" ],
            [ "code" => "EGP", "name" => "Egyptian pound", "symbol" => "£" ],
            [ "code" => "ERN", "name" => "Eritrean nakfa", "symbol" => "Nfk" ],
            [ "code" => "ETB", "name" => "Ethiopian birr", "symbol" => "Br" ],
            [ "code" => "FKP", "name" => "Falkland Islands pound", "symbol" => "£" ],
            [ "code" => "DKK", "name" => "Danish krone", "symbol" => "kr" ],
            [ "code" => "GMD", "name" => "Gambian dalasi", "symbol" => "D" ],
            [ "code" => "GEL", "name" => "Georgian Lari", "symbol" => "ლ" ],
            [ "code" => "GHS", "name" => "Ghanaian cedi", "symbol" => "₵" ],
            [ "code" => "GIP", "name" => "Gibraltar pound", "symbol" => "£" ],
            [ "code" => "DKK", "name" => "Danish krone", "symbol" => "kr" ],
            [ "code" => "GTQ", "name" => "Guatemalan quetzal", "symbol" => "Q" ],
            [ "code" => "GNF", "name" => "Guinean franc", "symbol" => "Fr" ],
            [ "code" => "HTG", "name" => "Haitian gourde", "symbol" => "G" ],
            [ "code" => "HNL", "name" => "Honduran lempira", "symbol" => "L" ],
            [ "code" => "HUF", "name" => "Hungarian forint", "symbol" => "Ft" ],
            [ "code" => "ISK", "name" => "Icelandic króna", "symbol" => "kr" ],
            [ "code" => "INR", "name" => "Indian rupee", "symbol" => "₹" ],
            [ "code" => "IDR", "name" => "Indonesian rupiah", "symbol" => "Rp" ],
            [ "code" => "IRR", "name" => "Iranian rial", "symbol" => "﷼" ],
            [ "code" => "IQD", "name" => "Iraqi dinar", "symbol" => "ع.د" ],
            [ "code" => "JPY", "name" => "Japanese yen", "symbol" => "¥" ],
            [ "code" => "JOD", "name" => "Jordanian dinar", "symbol" => "د.ا" ],
            [ "code" => "KWD", "name" => "Kuwaiti dinar", "symbol" => "د.ك" ],
            [ "code" => "KGS", "name" => "Kyrgyzstani som", "symbol" => "с" ],
            [ "code" => "LAK", "name" => "Lao kip", "symbol" => "₭" ],
            [ "code" => "LBP", "name" => "Lebanese pound", "symbol" => "ل.ل" ],
            [ "code" => "LSL", "name" => "Lesotho loti", "symbol" => "L" ],
            [ "code" => "LYD", "name" => "Libyan dinar", "symbol" => "ل.د" ],
            [ "code" => "MOP", "name" => "Macanese pataca", "symbol" => "P" ],
            [ "code" => "MKD", "name" => "Macedonian denar", "symbol" => "ден" ],
            [ "code" => "MGA", "name" => "Malagasy ariary", "symbol" => "Ar" ],
            [ "code" => "MWK", "name" => "Malawian kwacha", "symbol" => "MK" ],
            [ "code" => "MYR", "name" => "Malaysian ringgit", "symbol" => "RM" ],
            [ "code" => "MVR", "name" => "Maldivian rufiyaa", "symbol" => ".ރ" ],
            [ "code" => "MRO", "name" => "Mauritanian ouguiya", "symbol" => "UM" ],
            [ "code" => "MUR", "name" => "Mauritian rupee", "symbol" => "₨" ],
            [ "code" => "MDL", "name" => "Moldovan leu", "symbol" => "L" ],
            [ "code" => "MNT", "name" => "Mongolian tögrög", "symbol" => "₮" ],
            [ "code" => "MZN", "name" => "Mozambican metical", "symbol" => "MT" ],
            [ "code" => "MMK", "name" => "Burmese kyat", "symbol" => "Ks" ],
            [ "code" => "NPR", "name" => "Nepalese rupee", "symbol" => "₨" ],
            [ "code" => "NIO", "name" => "Nicaraguan córdoba", "symbol" => "C$" ],
            [ "code" => "NGN", "name" => "Nigerian naira", "symbol" => "₦" ],
            [ "code" => "KPW", "name" => "North Korean won", "symbol" => "₩" ],
            [ "code" => "OMR", "name" => "Omani rial", "symbol" => "ر.ع." ],
            [ "code" => "PKR", "name" => "Pakistani rupee", "symbol" => "₨" ],
            [ "code" => "PGK", "name" => "Papua New Guinean kina", "symbol" => "K" ],
            [ "code" => "PYG", "name" => "Paraguayan guaraní", "symbol" => "₲" ],
            [ "code" => "PEN", "name" => "Peruvian sol", "symbol" => "S/." ],
            [ "code" => "PHP", "name" => "Philippine peso", "symbol" => "₱" ],
            [ "code" => "PLN", "name" => "Polish złoty", "symbol" => "zł" ],
            [ "code" => "QAR", "name" => "Qatari riyal", "symbol" => "ر.ق" ],
            [ "code" => "RON", "name" => "Romanian leu", "symbol" => "lei" ],
            [ "code" => "RUB", "name" => "Russian ruble", "symbol" => "₽" ],
            [ "code" => "RWF", "name" => "Rwandan franc", "symbol" => "Fr" ],
            [ "code" => "SHP", "name" => "Saint Helena pound", "symbol" => "£" ],
            [ "code" => "WST", "name" => "Samoan tālā", "symbol" => "T" ],
            [ "code" => "STD", "name" => "São Tomé and Príncipe dobra", "symbol" => "Db" ],
            [ "code" => "SAR", "name" => "Saudi riyal", "symbol" => "ر.س" ],
            [ "code" => "RSD", "name" => "Serbian dinar", "symbol" => "дин." ],
            [ "code" => "SCR", "name" => "Seychellois rupee", "symbol" => "₨" ],
            [ "code" => "SLL", "name" => "Sierra Leonean leone", "symbol" => "Le" ],
            [ "code" => "ZAR", "name" => "South African rand", "symbol" => "R" ],
            [ "code" => "KRW", "name" => "South Korean won", "symbol" => "₩" ],
            [ "code" => "SSP", "name" => "South Sudanese pound", "symbol" => "£" ],
            [ "code" => "LKR", "name" => "Sri Lankan rupee", "symbol" => "Rs" ],
            [ "code" => "SDG", "name" => "Sudanese pound", "symbol" => "ج.س." ],
            [ "code" => "SZL", "name" => "Swazi lilangeni", "symbol" => "L" ],
            [ "code" => "SEK", "name" => "Swedish krona", "symbol" => "kr" ],
            [ "code" => "SYP", "name" => "Syrian pound", "symbol" => "£" ],
            [ "code" => "TJS", "name" => "Tajikistani somoni", "symbol" => "ЅМ" ],
            [ "code" => "THB", "name" => "Thai baht", "symbol" => "฿" ],
            [ "code" => "TOP", "name" => "Tongan paʻanga", "symbol" => "T$" ],
            [ "code" => "AED", "name" => "United Arab Emirates dirham", "symbol" => "د.إ" ],
            [ "code" => "VEF", "name" => "Venezuelan bolívar", "symbol" => "Bs F" ],
            [ "code" => "VND", "name" => "Vietnamese đồng", "symbol" => "₫" ],
            [ "code" => "YER", "name" => "Yemeni rial", "symbol" => "﷼" ],
        ];

        foreach( $currency AS $array )
            Currencs::create( $array );
    }
}
